sudo: false
language: java
jdk: openjdk8

# Skip default Travis ./gradle check script as the project has no tests
script: true

deploy:
  provider: script
  skip_cleanup: true
  script: .travis/secrets.sh && ./gradlew publish
  on:
    tags: true
